"""`spec-driven retry`. Owner: T2. Roll back to an earlier phase (design doc §8,
workflow §16): mark the phase's artifact as revised, reopen the phase, mark every
later phase that had started as stale, and withdraw user acceptance."""

import datetime

from .. import locate, meta, router
from ..errors import OK, fail
from ..project import Project

# Reports are regenerated by their agent (the first line must stay the generated-by
# marker), so only authored artifacts get the revision note.
AUTHORED = ("1", "2", "3", "4", "6")


def register(sub):
    p = sub.add_parser("retry", help="回退到某个 Phase")
    p.add_argument("phase")
    p.add_argument("--reason", required=True)
    p.add_argument("--change")


def _mark_revised(path, reason: str) -> None:
    if not path.is_file():
        return
    note = "<!-- revised at %s: %s -->\n" % (datetime.date.today().isoformat(), reason.replace("--", "—"))
    path.write_bytes((note + path.read_text(encoding="utf-8")).encode("utf-8"))


def check_rollback(m: dict, phase: str, reason: str) -> None:
    """fail() unless rolling back from the current phase to `phase` is allowed."""
    if phase not in meta.PHASES or phase == "0":
        fail("只能回退到 Phase %s" % " / ".join(meta.PHASES[1:]))
    if meta.PHASES.index(phase) >= meta.PHASES.index(m["phase"]):
        fail("当前在 Phase %s，只能回退到更早的 Phase" % m["phase"])
    if not (reason or "").strip():
        fail("--reason 不能为空")


def rollback(change_dir, phase: str, reason: str) -> dict:
    """Reopen `phase`, mark later started phases stale, withdraw acceptance; return the new meta."""
    target = meta.PHASES.index(phase)

    def apply(md):
        status = md["phaseStatus"]
        for p in meta.PHASES[target + 1:]:
            if status.get(p) in ("passed", "in_progress", "blocked"):
                status[p] = "stale"
        status[phase] = "in_progress"
        md["phase"] = phase
        md["staleFrom"] = phase
        if target <= meta.PHASES.index("8.9"):
            md["uatAccepted"], md["uatAcceptedAt"] = False, None

    m = meta.update(change_dir, apply)
    if phase in AUTHORED:
        _mark_revised(change_dir / router.OUTPUT[phase], reason)
    return m


def report(phase: str, m: dict) -> None:
    stale = router.stale_phases(m)
    print("已回退到 Phase %s（%s）。%s" % (phase, router.ACTIONS[phase],
          "之后需要重新过门：Phase %s" % "、".join(stale) if stale else ""))


def run(a) -> int:
    project = Project.here()
    change, change_dir, m = locate.load(project, a.change)
    check_rollback(m, a.phase, a.reason)
    report(a.phase, rollback(change_dir, a.phase, a.reason))
    return OK
