"""`reinsdev install / uninstall / update`.

The plugin is installed from the checkout reinsdev itself runs from: the
clone the one-line installer keeps in ~/.reins/src for users, or the working
tree for developers. Same code path either way:

  Claude Code, Codex  the checkout as local marketplace "reinsdev"
  Codex agents        converted from reinsdev-plugin/agents/*.md into ~/.codex/agents/
  OpenCode            a plugin file re-exporting reinsdev-plugin/index.js
  ~/.reins/installed.json  targets installed and files we created, for exact uninstall
"""

import json
import os
import subprocess
import sys
from pathlib import Path

from spec_driven.paths import reins_home

from . import PLUGIN, ROOT
from .agents import install_agents
from .platforms import TARGETS, codex_home, detected, find_cli, opencode_config_dir

MARKETPLACE = "reinsdev"
PLUGIN_ID = "reins@" + MARKETPLACE

OPENCODE_STUB = "reinsdev.js"
# Manifest key for agents written by `reinsdev setup codex` on a natively installed Codex plugin.
SETUP_KEY = "codex-agents"


class Installer:
    def __init__(self, dry_run=False, force=False):
        self.dry_run = dry_run
        self.force = force
        self.home = reins_home()
        self.manifest_path = self.home / "installed.json"
        self.manifest = {}
        if self.manifest_path.is_file():
            self.manifest = json.loads(self.manifest_path.read_text(encoding="utf-8"))

    def say(self, msg):
        print(("[dry-run] " if self.dry_run else "") + msg, flush=True)

    def save(self):
        if not self.dry_run:
            self.home.mkdir(parents=True, exist_ok=True)
            self.manifest_path.write_text(json.dumps(self.manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    def run_cmd(self, argv, tolerate=False):
        self.say("$ " + " ".join(argv))
        if self.dry_run:
            return True
        exe = find_cli(argv[0])  # also resolves claude.cmd / codex.cmd on Windows
        if not exe:
            raise SystemExit("reins: 找不到命令 %s" % argv[0])
        r = subprocess.run([exe] + argv[1:], capture_output=True, encoding="utf-8", errors="replace")
        out = ((r.stdout or "") + (r.stderr or "")).strip()
        if out:
            print("  " + out.replace("\n", "\n  "), flush=True)
        if r.returncode != 0 and not tolerate:
            raise SystemExit("reins: 命令失败（退出码 %d）：%s" % (r.returncode, " ".join(argv)))
        return r.returncode == 0

    def known_files(self):
        return set(f for entry in self.manifest.values() for f in entry.get("files", []))

    # --- runtimes ------------------------------------------------------
    def install_claude(self):
        self.run_cmd(["claude", "plugin", "marketplace", "add", str(ROOT)], tolerate=True)
        self.run_cmd(["claude", "plugin", "marketplace", "update", MARKETPLACE], tolerate=True)
        if not self.run_cmd(["claude", "plugin", "install", PLUGIN_ID], tolerate=True):
            self.run_cmd(["claude", "plugin", "update", PLUGIN_ID])
        return []

    def install_codex(self):
        self.run_cmd(["codex", "plugin", "marketplace", "add", str(ROOT)], tolerate=True)
        if not self.run_cmd(["codex", "plugin", "add", PLUGIN_ID], tolerate=True):
            # Codex has no `plugin update`: reinstall to pick up changes.
            self.run_cmd(["codex", "plugin", "remove", PLUGIN_ID], tolerate=True)
            self.run_cmd(["codex", "plugin", "add", PLUGIN_ID])
        dest = codex_home() / "agents"
        self.say("安装 Codex agents → %s" % dest)
        if self.dry_run:
            return []
        return install_agents(dest, self.force, self.known_files())

    def install_opencode(self):
        stub = opencode_config_dir() / "plugins" / OPENCODE_STUB
        if stub.exists() and str(stub) not in self.known_files() and not self.force:
            raise SystemExit("reins: %s 已存在且不是 Reins 安装的，拒绝覆盖（确认无误可加 --force）" % stub)
        entry = (PLUGIN / "index.js").resolve()
        self.say("写入 %s → %s" % (stub, entry))
        if not self.dry_run:
            stub.parent.mkdir(parents=True, exist_ok=True)
            stub.write_bytes(('// Reins for OpenCode; generated by reinsdev install\n'
                              'export * from "%s"\n' % entry.as_uri()).encode("utf-8"))
        return [str(stub)]

    def install(self, targets):
        for t in targets:
            self.say("== %s ==" % t)
            self.manifest[t] = {"files": getattr(self, "install_" + t)()}
        self.save()

    def uninstall(self, targets):
        for t in targets:
            self.say("== %s ==" % t)
            if t == "claude":
                self.run_cmd(["claude", "plugin", "uninstall", PLUGIN_ID], tolerate=True)
                self.run_cmd(["claude", "plugin", "marketplace", "remove", MARKETPLACE], tolerate=True)
            if t == "codex":
                self.run_cmd(["codex", "plugin", "remove", PLUGIN_ID], tolerate=True)
                self.run_cmd(["codex", "plugin", "marketplace", "remove", MARKETPLACE], tolerate=True)
            keys = [t, SETUP_KEY] if t == "codex" else [t]
            for f in [f for k in keys for f in self.manifest.get(k, {}).get("files", [])]:
                self.say("删除 %s" % f)
                if not self.dry_run and os.path.exists(f):
                    os.remove(f)
            for k in keys:
                self.manifest.pop(k, None)
        self.save()


def resolve_targets(target: str):
    if target == "all":
        return list(TARGETS)
    if target == "detected":
        found = detected()
        if not found:
            raise SystemExit("reins: 没有检测到 claude / codex / opencode")
        return found
    names = [t for t in target.split(",") if t]
    bad = [t for t in names if t not in TARGETS]
    if bad or not names:
        raise SystemExit("reins: 未知平台 %s（可选 %s、all、detected）" % (",".join(bad) or target, "、".join(TARGETS)))
    return names


def run_install(target, dry_run, force):
    Installer(dry_run, force).install(resolve_targets(target))
    return 0


def run_uninstall(target, dry_run):
    Installer(dry_run).uninstall(resolve_targets(target))
    return 0


def run_setup(runtime, project, force):
    if runtime != "codex":
        print("%s 不需要额外设置。" % runtime)
        return 0
    inst = Installer(force=force)
    dest = (Path.cwd() / ".codex" / "agents") if project else codex_home() / "agents"
    files = install_agents(dest, force, inst.known_files())
    for f in files:
        print("已安装 %s" % f)
    old = inst.manifest.get(SETUP_KEY, {}).get("files", [])
    inst.manifest[SETUP_KEY] = {"files": sorted(set(old) | set(files))}
    inst.save()
    print("完成。请重启 Codex 使 agent 生效。")
    return 0


def managed_clone() -> bool:
    """True when running from the one-line installer's clone, not a working tree."""
    return ROOT.resolve() == (reins_home() / "src").resolve()


def run_update(dry_run):
    """Pull the managed clone, then reinstall the targets installed before."""
    targets = [t for t in TARGETS if t in Installer().manifest]
    if not targets:
        raise SystemExit("reins: 还没有用 reinsdev 安装过任何平台，请先运行 reinsdev install")
    if managed_clone():
        print("$ git -C %s pull --ff-only" % ROOT, flush=True)
        if not dry_run:
            subprocess.run(["git", "-C", str(ROOT), "pull", "--ff-only"], check=True)
    else:
        print("开发仓库 %s：不拉取更新，直接用工作区重装" % ROOT, flush=True)
    # Re-exec so the reinstall runs the freshly pulled code.
    argv = [sys.executable, str(ROOT / "bin" / "reinsdev.py"), "install", "--target", ",".join(targets)]
    if dry_run:
        argv.append("--dry-run")
    return subprocess.run(argv).returncode
