#!/bin/sh
# Reins one-line installer (macOS / Linux / Git Bash on Windows):
#   curl -fsSL https://raw.githubusercontent.com/reinsdev/reins/main/install.sh | sh
#   curl -fsSL ... | sh -s -- --target codex       # arguments go to `reinsdev install`
# Keeps the source in ~/.reins/src, puts the reinsdev launcher in ~/.reins/bin,
# then installs into every detected platform. Run from a checkout
# (./install.sh), it installs that working tree instead, for development.
# Environment: REINS_HOME (default ~/.reins), REINS_REPO, REINS_REF (default main).
set -e
REPO=${REINS_REPO:-https://github.com/reinsdev/reins.git}
REF=${REINS_REF:-main}
RHOME=${REINS_HOME:-$HOME/.reins}

case "$0" in
  *install.sh)
    SRC=$(cd "$(dirname "$0")" && pwd) ;;
  *)
    SRC="$RHOME/src"
    command -v git >/dev/null 2>&1 || { echo "reins: 需要 git" >&2; exit 1; }
    if [ -d "$SRC/.git" ]; then
      git -C "$SRC" pull -q --ff-only
    else
      mkdir -p "$RHOME"
      git clone -q --depth 1 --branch "$REF" "$REPO" "$SRC"
    fi ;;
esac

DRY=
for a in "$@"; do [ "$a" = "--dry-run" ] && DRY=1; done

if [ -z "$DRY" ]; then
mkdir -p "$RHOME/bin"
cat > "$RHOME/bin/reinsdev" <<EOF
#!/bin/sh
# Generated by the Reins installer.
: "\${REINS_HOME:=$RHOME}"
export REINS_HOME
exec "$SRC/bin/reinsdev" "\$@"
EOF
chmod +x "$RHOME/bin/reinsdev"
fi

REINS_HOME=$RHOME
export REINS_HOME
"$SRC/bin/reinsdev" install "$@"
"$SRC/bin/reinsdev" doctor

case ":$PATH:" in
  *":$RHOME/bin:"*) ;;
  *) printf '\n把 reinsdev 加入 PATH（写进 ~/.zshrc 或 ~/.bashrc）：\n  export PATH="%s/bin:$PATH"\n' "$RHOME" ;;
esac
