# Reins one-line installer (Windows PowerShell):
#   irm https://raw.githubusercontent.com/reinsdev/reins/main/install.ps1 | iex
# Keeps the source in ~\.reins\src, puts reinsdev.cmd in ~\.reins\bin (added to
# the user PATH), then installs into every detected platform. Run from a
# checkout (.\install.ps1 [--target ...]), it installs that working tree instead.
# Environment: REINS_HOME, REINS_REPO, REINS_REF (default main), REINS_TARGET.
$ErrorActionPreference = "Stop"
$repo = if ($env:REINS_REPO) { $env:REINS_REPO } else { "https://github.com/reinsdev/reins.git" }
$ref = if ($env:REINS_REF) { $env:REINS_REF } else { "main" }
$rhome = if ($env:REINS_HOME) { $env:REINS_HOME } else { Join-Path $HOME ".reins" }

if ($PSCommandPath) {
  $src = Split-Path -Parent $PSCommandPath
} else {
  $src = Join-Path $rhome "src"
  if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw "reins: 需要 git（Git for Windows）" }
  if (Test-Path (Join-Path $src ".git")) {
    git -C $src pull -q --ff-only
  } else {
    New-Item -ItemType Directory -Force $rhome | Out-Null
    git clone -q --depth 1 --branch $ref $repo $src
  }
  if ($LASTEXITCODE -ne 0) { throw "reins: 获取源码失败" }
}

$installArgs = @($args)
if ($env:REINS_TARGET) { $installArgs += @("--target", $env:REINS_TARGET) }
$dryRun = $installArgs -contains "--dry-run"

$bin = Join-Path $rhome "bin"
if (-not $dryRun) {
New-Item -ItemType Directory -Force $bin | Out-Null
$launcher = "@echo off`r`nrem Generated by the Reins installer.`r`nif not defined REINS_HOME set `"REINS_HOME=$rhome`"`r`n`"$src\bin\reinsdev.cmd`" %*`r`n"
[IO.File]::WriteAllText((Join-Path $bin "reinsdev.cmd"), $launcher, [Text.Encoding]::Default)

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (-not (($userPath -split ";") -contains $bin)) {
  [Environment]::SetEnvironmentVariable("Path", ((@($bin, $userPath) | Where-Object { $_ }) -join ";"), "User")
  Write-Host "已把 $bin 加入用户 PATH，新开的终端里可以直接运行 reinsdev。"
}
}

$env:REINS_HOME = $rhome
& (Join-Path $src "bin\reinsdev.cmd") install @installArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
& (Join-Path $src "bin\reinsdev.cmd") doctor
